name = 'dailyimage-generator'
main = 'src/index.ts'
compatibility_date = '2024-02-08'

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ['0 0 * * *']

[ai]
binding = 'AI'

[[r2_buckets]]
bucket_name = 'dailyimage'
preview_bucket_name = 'dailyimage-dev'
binding = 'IMAGE_BUCKET'